version: "3"

services:

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8009:8009"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8009/health"]    
    restart: always

  frontend:
    build: 
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8080:8080" 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
    depends_on:
      - backend
    restart: on-failure
   
