version: "3"

services:

  frontend:
    build: ./app
    ports:
      - "8080:8080"
    links:
      - backend

  backend:
    build: ./server  
    ports:
      - "8009:8009"
    links:
      - frontend